displayName=Arachnophobia Mode
author=Danders
description=Obscures spiders and custom user-defined NPCs
tags=arachnophobia, spider, hide
version=1.0.0
plugins=com.danders.ArachnophobiaPlugin
build=standard